### PR TITLE
Fix call to to unwait in stop

### PR DESCRIPTION
**Pull request by jakesjews**

### CODE REVIEW

**Comment by ichernev** [comment]
Ah, my bad. Can you also add a test that covers that case?

**Comment by jakesjews** [comment]
No problem. I'm a little busy this weekend but I can get to it next week.

**Comment by jakesjews** [comment]
Turns out I did have some time. Is this test ok? Its a little weird since the listeners are properly being unregistered so I can only really test that the timer never actually fired.

**Comment by jakesjews** [comment]
@ichernev any updates on this PR?

**Comment by jakesjews** [comment]
:+1: thanks for the merge!

**Comment by ichernev** [comment]
I'll release a version in a few hours. My current computer doesn't have npm creds :(

**Comment by ichernev** [comment]
Version 1.4.4 contains the change.

**Pull request merged**
